version: "{build} - {branch}"
skip_tags: true
skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test
  - npm i -g codecov
  - codecov

build: off
