language: node_js
node_js:
- '5'
deploy:
  provider: npm
  email: christoph.buehler@bluewin.ch
  api_key:
    secure: Wf261yduxABD9qbUJVVWfXpXK3+RwSrkt16iEmxQRNRtY8SMGyOBWymZSDfTUyyDPzjR3wCgUbk0xNVUEClBxojPPjNsROeeLnggObZU6KDEOySyCdB6hNXryNAeemOlxHEP9ktujl857Ok1e+EaB08pAvwPhkx+wCNv4ILLLERWJMRAcwT0cU8TeQBwwLJTGEo8JKTfQPezKIZLu0JfBDSVg2tnMPfwFjb/3HijsBDdVkmWNrOyiEaS3PG3puvGYPQrnPH1XwFZgEJYmRDEJdA/LMQxRDRj7Tn+VzL1mOIDx9193+Md8f9+vX6Fo1wI/H/hThVF5TAankJbr3p5I6JclN0y7yYgQBceNTsBupzBrZqqMhhtDeV6v793InrghrD+FOpnV51rf1z8Y7Eiyz/fKAEDsFw9TE8WKzPmzwhVVvn+BHe8LAo7D4QvH5JhneAnpCLG15l6dfCDFFuJ/cdP11d3N/ueeuYdiPmtCUfqyE7mgj4uX5Q1urTIQtY7Cs8RDOa+H1IwZIhRRiOe0Q8KAu2Bdpvuru67TSmx3XBtFyvsuN71DNACFnlvtbDce/xGoDN0icNG0jSEdCvsXKs2kRfCJ9eoHPgvqbjsPxgWyr9k2CSD/ZrkJo9dphBvt+Y2rDeFVAVfAKX0qXj+z7G839ToWtZQaTjF3UYRXPo=
  on:
    tags: true
    repo: smartive/giuseppe
